version: '3'
services:
  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672'
      - '15672:15672'
  user-service:
    build: ./user-service
    ports:
      - '3001:3001'
    depends_on:
      - rabbitmq
  order-service:
    build: ./order-service
    ports:
      - '3002:3002'
    depends_on:
      - rabbitmq
